"""added subscription and create relationship with user class

Revision ID: 08526e91f40e
Revises: 735a1ddb58d8
Create Date: 2025-09-16 17:28:44.855254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08526e91f40e'
down_revision = '735a1ddb58d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('paypal_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('credits_per_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_subscription_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_expiry_date')
        batch_op.drop_column('paypal_subscription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_subscription_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subscription_expiry_date', sa.DATE(), nullable=True))

    op.drop_table('subscription')
    # ### end Alembic commands ###
