"""empty message

Revision ID: 091dbea6730e
Revises: 31ead2a5caaa
Create Date: 2025-12-26 16:05:08.732410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '091dbea6730e'
down_revision = '31ead2a5caaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_column('amount')
        batch_op.drop_column('reason')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_used_free_event')
        batch_op.drop_column('event_credits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_credits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('has_used_free_event', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    with op.batch_alter_table('credit_grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('source_type')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
