"""add full_address to Event Model

Revision ID: 193edc6374c8
Revises: 2f03bd62f188
Create Date: 2025-07-28 22:40:47.467531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193edc6374c8'
down_revision = '2f03bd62f188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('full_address')

    # ### end Alembic commands ###
