"""ttendeee list

Revision ID: 1d68004b2b10
Revises: 2a334b9759f0
Create Date: 2025-06-12 14:37:25.504099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d68004b2b10'
down_revision = '2a334b9759f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
