"""added guest_count to EventAttendee

Revision ID: 2a334b9759f0
Revises: fba5588f36aa
Create Date: 2025-06-12 13:35:03.775005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a334b9759f0'
down_revision = 'fba5588f36aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_count', sa.Integer(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('guest_count')

    # ### end Alembic commands ###
