"""fix guest_count

Revision ID: 2f03bd62f188
Revises: 1d68004b2b10
Create Date: 2025-06-12 17:49:38.889729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f03bd62f188'
down_revision = '1d68004b2b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.alter_column('guest_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.alter_column('guest_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
