"""add display_name to User model

Revision ID: 309a7d607688
Revises: 65428f07d8c8
Create Date: 2025-07-31 16:14:28.943978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309a7d607688'
down_revision = '65428f07d8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
