"""added ticket price

Revision ID: 41e1ccfd9625
Revises: ca2ae170cdb1
Create Date: 2025-05-06 17:27:41.288889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e1ccfd9625'
down_revision = 'ca2ae170cdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('ticket_price')

    # ### end Alembic commands ###
