"""add merchandise shipping address

Revision ID: 45d9b435c77a
Revises: b82e6a3e87ad
Create Date: 2026-07-31 14:19:07.286173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d9b435c77a'
down_revision = 'b82e6a3e87ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merch_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_line_1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_line_2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('shipping_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merch_orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_amount')
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_postal_code')
        batch_op.drop_column('shipping_state')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address_line_2')
        batch_op.drop_column('shipping_address_line_1')
        batch_op.drop_column('shipping_name')

    # ### end Alembic commands ###
