"""Add address to User model

Revision ID: 65428f07d8c8
Revises: 193edc6374c8
Create Date: 2025-07-29 17:57:45.703333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65428f07d8c8'
down_revision = '193edc6374c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
