"""Add paypal_subscription_id to User model

Revision ID: 735a1ddb58d8
Revises: b5881aa81623
Create Date: 2025-08-18 22:45:13.940749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735a1ddb58d8'
down_revision = 'b5881aa81623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_subscription_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('paypal_subscription_id')

    # ### end Alembic commands ###
