"""add subscription and free event fields to user model

Revision ID: b5881aa81623
Revises: 309a7d607688
Create Date: 2025-08-04 17:26:28.507403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5881aa81623'
down_revision = '309a7d607688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_used_free_event', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('event_credits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subscription_expiry_date', sa.Date(), nullable=True))
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('subscription_expiry_date')
        batch_op.drop_column('event_credits')
        batch_op.drop_column('has_used_free_event')

    # ### end Alembic commands ###
