"""add merchandise orders

Revision ID: b82e6a3e87ad
Revises: 052945c16060
Create Date: 2026-07-31 11:35:21.387661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82e6a3e87ad'
down_revision = '052945c16060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merch_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_email', sa.String(length=150), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('fulfillment_method', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=255), nullable=True),
    sa.Column('paypal_capture_id', sa.String(length=255), nullable=True),
    sa.Column('paypal_payer_email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    sa.UniqueConstraint('paypal_capture_id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    op.create_table('merch_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merch_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['merch_order_id'], ['merch_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merch_order_items')
    op.drop_table('merch_orders')
    # ### end Alembic commands ###
