"""add guest fields to Event model

Revision ID: ca2ae170cdb1
Revises: d6ec6fe093a2
Create Date: 2025-05-05 17:04:47.862123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2ae170cdb1'
down_revision = 'd6ec6fe093a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_guests', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('guest_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('guest_limit')
        batch_op.drop_column('allow_guests')

    # ### end Alembic commands ###
