"""username removed, keep email

Revision ID: ff6453c2f56f
Revises: a3cfd2abdd11
Create Date: 2024-12-04 14:21:32.067874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff6453c2f56f'
down_revision = 'a3cfd2abdd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=150), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
